import type { NextPage } from "next";
import Head from "next/head";

import { useState } from "react";

import InputForm from "@components/InputForm/index";
import Output from "@components/Output/index";

const Home: NextPage = () => {
  const [OutputData, setOutput] = useState("");

  return (
    <section className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <InputForm setOutput={setOutput} />
      <Output data={OutputData} />
    </section>
  );
};

export default Home;
