import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { useState } from "react";

import { generate } from "../functions/generate";

const Home: NextPage = () => {
  const [name, setName] = useState("");
  const [symbol, setSymbol] = useState("");
  const [decimals, setDecimals] = useState(18);
  const [initialSupply, setInitialSupply] = useState(1000);

  const [Output, setOutput] = useState("");

  const runGenerate = (e: any) => {
    e.preventDefault();

    setOutput(
      generate({
        name,
        symbol,
        decimals,
        initialSupply,
      })
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form action="" onSubmit={runGenerate}>
        <input
          type=""
          placeholder="Token Name here:"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
        <br />
        <input
          type="text"
          placeholder="Token Symbol here:"
          value={symbol}
          onChange={(e) => setSymbol(e.target.value)}
        />
        <br />
        <input
          type="number"
          placeholder="Token decimals here:"
          value={decimals}
          onChange={(e) => setDecimals(Number(e.target.value))}
        />
        <br />
        <input
          type="number"
          placeholder="Token Suppply:"
          value={initialSupply}
          onChange={(e) => setInitialSupply(Number(e.target.value))}
        />
        <br />
        <button>Generate Token</button>
      </form>

      <div className="output">
        <pre>
          <code>{Output}</code>
        </pre>
      </div>
    </div>
  );
};

export default Home;
